import type { Deal } from "./types";

const now = Date.now();
const minutes = (m: number) => new Date(now - m * 60_000).toISOString();

export const INITIAL_DEALS: Deal[] = [
  {
    id: 187,
    status: "new",
    client: "Надежда",
    phone: "+7 701 443-84-93",
    city: "Алматы",
    service: "moskitka",
    comment: "Здравствуйте! Пишу с сайта moskitnyesetki.kz. Подскажите, фальш...",
    responsible: "Динар",
    createdAt: minutes(15),
    updatedAt: minutes(8),
    source: "site",
    attachments: [],
    chat: [
      { id: "m1", author: "Надежда", text: "Здравствуйте! Нужны сетки на 4 окна.", at: minutes(15), fromClient: true },
    ],
    unread: 1,
  },
  {
    id: 186,
    status: "new",
    client: "Новый (Bitrotel)",
    phone: "+7 717 197-34-106",
    city: "Астана",
    service: "okno",
    comment: "Входящий звонок",
    responsible: "Алекс",
    createdAt: minutes(35),
    updatedAt: minutes(35),
    source: "call",
    attachments: [],
    chat: [],
    unread: 0,
  },
  {
    id: 185,
    status: "new",
    client: "sqgg6343",
    phone: "+7 707 427-66-92",
    city: "Караганда",
    service: "moskitka",
    comment: "Здравствуйте, пишу с сайта eco-service.kz по поводу москитных сеток, гор...",
    responsible: "Андрей",
    createdAt: minutes(60),
    updatedAt: minutes(45),
    source: "site",
    attachments: [],
    chat: [],
    unread: 0,
  },
  {
    id: 182,
    status: "overdue",
    client: "Максим",
    phone: "+7 770 805-77-11",
    city: "Алматы",
    service: "moskitka",
    comment: "Текст: Здравствуйте! Пишу с сайта eko-plastikovye.kz. Хочу получить консультацию.",
    responsible: "Старший оператор",
    createdAt: minutes(60 * 24 + 120),
    updatedAt: minutes(60 * 12),
    source: "site",
    attachments: [],
    chat: [],
    unread: 0,
  },
  {
    id: 181,
    status: "overdue",
    client: "Hanna",
    phone: "+7 705 561-75-39",
    city: "Шымкент",
    service: "plisse",
    comment: "Здравствуйте! Пишу с сайта eko-plastikovye.kz. Хочу получить консультацию.",
    responsible: "Старший оператор",
    createdAt: minutes(60 * 28),
    updatedAt: minutes(60 * 14),
    source: "site",
    attachments: [],
    chat: [],
    unread: 2,
  },
  {
    id: 180,
    status: "overdue",
    client: "Клиент 77013636108",
    phone: "+7 701 363-61-08",
    city: "Алматы",
    service: "remont",
    comment: "Текст: Медиа/Файл",
    responsible: "Старший оператор",
    createdAt: minutes(60 * 30),
    updatedAt: minutes(60 * 15),
    source: "whatsapp",
    attachments: [{ id: "a1", name: "okno.jpg", size: 482000, kind: "photo" }],
    chat: [],
    unread: 0,
  },
  {
    id: 178,
    status: "manager",
    client: "Nuraly",
    phone: "+7 701 077-72-27",
    city: "Алматы",
    service: "moskitka",
    address: "ул. Абая, д. 12",
    comment: "Текст: Медиа/Файл. Дует из окна, нужна консультация.",
    responsible: "Алекс",
    createdAt: minutes(60 * 4),
    updatedAt: minutes(20),
    source: "whatsapp",
    amount: 28500,
    attachments: [{ id: "a2", name: "zamer.pdf", size: 124000, kind: "doc" }],
    chat: [
      { id: "m2", author: "Nuraly", text: "Добрый день, можно сегодня замерщика?", at: minutes(60 * 4), fromClient: true },
      { id: "m3", author: "Алекс", text: "Здравствуйте! Сейчас уточню график.", at: minutes(60 * 3) },
    ],
    unread: 0,
  },
  {
    id: 175,
    status: "measurer",
    client: "Айгуль",
    phone: "+7 707 100-23-45",
    city: "Алматы",
    service: "okno",
    address: "мкр. Самал-2, 14",
    comment: "Замер 3 окна на кухне и зале",
    responsible: "Замерщик Ержан",
    createdAt: minutes(60 * 26),
    updatedAt: minutes(60 * 2),
    source: "call",
    amount: 320000,
    attachments: [],
    chat: [],
    unread: 0,
  },
  {
    id: 170,
    status: "finance",
    client: "ТОО АстанаДом",
    phone: "+7 717 222-11-09",
    city: "Астана",
    service: "okno",
    comment: "Счёт на оплату партии 12 окон",
    responsible: "Финансист Мария",
    createdAt: minutes(60 * 48),
    updatedAt: minutes(60 * 6),
    source: "site",
    amount: 1840000,
    attachments: [],
    chat: [],
    unread: 0,
  },
  {
    id: 165,
    status: "done",
    client: "Дарина",
    phone: "+7 705 333-22-11",
    city: "Алматы",
    service: "moskitka",
    comment: "Установка завершена, отзыв 5★",
    responsible: "Алекс",
    createdAt: minutes(60 * 72),
    updatedAt: minutes(60 * 24),
    source: "instagram",
    amount: 42000,
    attachments: [],
    chat: [],
    unread: 0,
  },
];

export const RANDOM_NAMES = [
  "Алия",
  "Иван",
  "Жанар",
  "Сергей",
  "Мадина",
  "Бауржан",
  "Елена",
  "Ольга",
  "Ержан",
  "Тимур",
];

export const RANDOM_COMMENTS = [
  "Здравствуйте, нужна консультация по москитным сеткам.",
  "Хочу заменить уплотнитель на пластиковом окне.",
  "Подскажите цену на плиссе для балкона.",
  "Нужен замерщик на завтра, есть возможность?",
  "Окно не закрывается, требуется ремонт фурнитуры.",
];
